---
deployment:
  tasks:
    - export DEPLOYPATH=/home7/simiplus/public_html
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH

    - |
      if grep -q "GIT_COMMIT" $DEPLOYPATH/.env; then
        # Si existe, actualizarla con el nuevo valor
        sed -i "s/^GIT_COMMIT=.*/GIT_COMMIT=$(curl -s https://api.github.com/repos/WilliamsBD8/maxifritos/commits | jq -r '.[0].sha')/" $DEPLOYPATH/.env
      else
        # Si no existe, agregarla al final del archivo
        echo "GIT_COMMIT=$(curl -s https://api.github.com/repos/WilliamsBD8/maxifritos/commits | jq -r '.[0].sha')" >> $DEPLOYPATH/.env
      fi